---
gpus: 0
log_every_n_steps: 5
benchmark: True
precision: 32
gradient_clip_val: 5.0
num_sanity_val_steps: 0
max_epochs: 2
accelerator: auto

callbacks:
  EarlyStopping:
    monitor: val_loss
    min_delta: 0.001
    patience: 50
    verbose: True
    mode: min
  ModelCheckpoint:
    monitor: val_loss
    verbose: True
    mode: min
    save_top_k: 5
    every_n_epochs: 10
  RichProgressBar:
    refresh_rate_per_second: 10
  RichModelSummary:
    max_depth: 2
  Timer:
    duration: 00:00:05:30
  LearningRateMonitor:
    logging_interval: epoch