---
gpus: 1
log_every_n_steps: 5
benchmark: True
precision: 32
gradient_clip_val: 5.0
num_sanity_val_steps: 3
max_epochs: 150
accelerator: auto

callbacks:
  EarlyStopping:
    monitor: val_loss
    min_delta: 0.0001
    patience: 50
    verbose: True
    mode: min
  ModelCheckpoint:
    monitor: val_loss
    verbose: True
    mode: min
    save_top_k: 5
    every_n_epochs: 11
  RichProgressBar: { }
  LearningRateMonitor:
    logging_interval: epoch
  Timer:
    duration: 00:01:50:00